[theme]
base = "dark"
primaryColor = "#00f2ff"
backgroundColor = "#0a0a0b"
secondaryBackgroundColor = "#0e1117"
textColor = "#e0e0e0"
font = "sans serif"

[server]
headless = false
maxUploadSize = 50

[browser]
gatherUsageStats = false
